In [1]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('./remote_work_productivity.csv')
df.head()

,Employee_ID,Employment_Type,Hours_Worked_Per_Week,Productivity_Score,Well_Being_Score
0,1,Remote,29,75,78
1,2,In-Office,45,49,47
2,3,Remote,34,74,89
3,4,Remote,25,81,84
4,5,Remote,50,70,74

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            1000 non-null   int64
 1   Employment_Type        1000 non-null   object
 2   Hours_Worked_Per_Week  1000 non-null   int64
 3   Productivity_Score     1000 non-null   int64
 4   Well_Being_Score       1000 non-null   int64
dtypes: int64(4), object(1)
memory usage: 39.2+ KB

In [10]:
df.shape

(1000, 5)

In [12]:
# check unique values in employment_type
df['Employment_Type'].unique()

array(['Remote', 'In-Office'], dtype=object)

In [14]:
import numpy as np

# randomly convert 20% of Remote employees to Hybrid
mask = (df['Employment_Type'] == 'Remote') & (np.random.rand(len(df)) < 0.2)
df.loc[mask, 'Employment_Type'] = 'Hybrid'

In [15]:
# now check the unique values again
df['Employment_Type'].unique()

array(['Hybrid', 'In-Office', 'Remote'], dtype=object)

In [16]:
df.head()

,Employee_ID,Employment_Type,Hours_Worked_Per_Week,Productivity_Score,Well_Being_Score
0,1,Hybrid,29,75,78
1,2,In-Office,45,49,47
2,3,Hybrid,34,74,89
3,4,Remote,25,81,84
4,5,Remote,50,70,74

In [17]:
# save the modified dataframe to a new CSV file
df.to_csv('./remote_work_productivity_modified.csv', index=False)